# Generated by Django 4.1.1 on 2022-10-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writting',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
